### ISSUE TITLE
Icons in Items generating errors

### ISSUE THREAD

**Issue by jdgcoop** [Sk1mble/fate-core-official#16]
When I try to set the icon for an Item to something custom from my assets folders, I get a caching error.  I am hosted on The Forge, so if you don't see something in the module code, maybe it's an issue with the hosting environment.  Hard to describe so I recorded it happening here: https://www.loom.com/share/8f6fecebcafe4889b1f1405b85e28f3f

**Comment by Sk1mble** [comment]
Fixed in v4.2.06
