### ISSUE TITLE
html insert in character sheet description field

### ISSUE THREAD

**Issue by jasharen** [Sk1mble/fate-core-official#19]
When inserting html into an actor's description field, it appears that it treats it as a hyper link regardless of what values are put in.

**Comment by Sk1mble** [comment]
I need more information on this, please. The </> button in the Pen editor
is working for me to format text as HTML.

**Comment by Sk1mble** [comment]
Added a new feature for you to assist with this in 4.2.17. Right click on a character's Notes, Biography, or Description to pop up a raw HTML editor.

I may bring this to other rich text fields later, but I thought these had priority.

**Comment by Sk1mble** [comment]
All rich text fields have this ability as of v4.2.18

**Comment by jasharen** [comment]
@Sk1mble You are amazing. Sorry for radio silence, real life for last couple days. I'll download today and test.
