### ISSUE TITLE
Actor Sheet - Aspects Description Field - larger than one line?

### ISSUE THREAD

**Issue by buttonpushertv** [Sk1mble/fate-core-official#2]
Could the text field for each Aspect on the Actor Sheet be more responsive to multi-line entries?

![screenshot 1620498275](https://user-images.githubusercontent.com/24526709/117549936-37123100-b00b-11eb-9d17-76f97b69146c.png)

**Comment by Sk1mble** [comment]
That's what the aspect notes field is for? It expands with the little
expand icon. It's not rich text though.

**Comment by buttonpushertv** [comment]
I see now how that works.
