### ISSUE TITLE
Won't update to 4.3.4

### ISSUE THREAD

**Issue by miromonti** [Sk1mble/fate-core-official#24]
Fate Core won't update from 4.3.3 to 4.3.4. I consistently receive this message:
![Screen Shot 2022-01-15 at 11 32 01 AM](https://user-images.githubusercontent.com/38819125/149635570-0c758ca1-31cd-4328-adac-e79ace335502.png)
I always respond Yes and the update seems to happen, but the result is always 4.3.3. I went so far as to uninstall and reinstall, but the result is the same, whether it's from the package installer or copy-paste the manifest URL.

**Comment by Sk1mble** [comment]
This is fixed now. I had failed to update the version info in system.json so it was still pointing to the old file.

**Comment by miromonti** [comment]
Thanks for the prompt response and resolution!
