### ISSUE TITLE
Initiative roll 1d0

### ISSUE THREAD

**Issue by jasharen** [Sk1mble/fate-core-official#25]
I'm trying to set up initiative, I have assigned Alertness as the skill driving initiative.

However, when I roll initiative in the combat tracker I am getting 1d0+Alterness instead of a normal fate roll?

**Comment by Sk1mble** [comment]
That's how initiative works in Fate Core:
https://fate-srd.com/fate-core/turn-order

You don't roll for initiative, you just act in order of the initiative skill.

**Comment by jasharen** [comment]
Sk1mble, sorry about that. I've been playing with a house rule so I'd forgotten core fate has static initiative. Is there any chance of being able to flag a house rule to actually roll initiative for those that want a little randomness in their battle order?

**Comment by Sk1mble** [comment]
No, but you could probably do it with a macro or module.

**Comment by jasharen** [comment]
@Sk1mble Are you adverse to me submitting a pull request? I've updated the code and added an option to the config settings?

fco.js

line 851
 game.settings.register("fate-core-official","randomRollSetting", {
        name:game.i18n.localize("fate-core-official.randomRollSetting"),
        hint:game.i18n.localize("fate-core-official.randomRollSettingExplainer"),
        scope:"world",
        config:"true",
        type:Boolean,
        default:false
    })

Then update _getInitiativeFormula:

Combatant.prototype._getInitiativeFormula = function () {
        let init_skill = game.settings.get("fate-core-official","init_skill");
	let randomRollSetting = game.settings.get("fate-core-official","randomRollSetting");
	
	if (randomRollSetting === true ) {
	 	if (init_skill === "None" || init_skill === "Disable") {
	 		return "4df";
	 	}else {
	 		return `4df+${this.actor.data.data.skills[init_skill].rank}`;
	 	}
	 }else {
		if (init_skill === "None" || init_skill === "Disable") {
			return "1d0";
		}else {
			return `1d0+${this.actor.data.data.skills[init_skill].rank}`;
		}
	 }
}

And en.json

   "fate-core-official.randomRollSetting":"Randomize initiative?",
   "fate-core-official.randomRollSettingExplainer":"Override normal core fate initiative by adding a random element to the initiative order."

**Comment by kondziu** [comment]
This is useful for off-nominal Fate-based systems (that I'm interested in). It would appear that the comment above never made it into the code. Is there any specific reason?

**Comment by Sk1mble** [comment]
I didn't want to. It's too far beyond what's standard for Fate for me to
support it.
However, you can write a world module that can achieve this by overriding
the following method:

Combatant.prototype._getInitiativeFormula = function () {
    let init_skill = game.settings.get("fate-core-official","init_skill");
    if (init_skill === "None" || init_skill === "Disable") {
        return "1d0";
    }else {
        return `1d0+${this.actor.system.skills[init_skill].rank}`;
    }
}

Kind regards,

Richard
