### ISSUE TITLE
Baileywiki Maps Pack

### ISSUE THREAD

**Issue by jasharen** [Sk1mble/fate-core-official#27]
When trying to import Bailywiki map pack I am getting an error that says:
The provided Actor type must be in the array of types defined by the game system.

I approached the content creator first, but they've highlighted that they believe it is a framework issue.

Thanks!

**Comment by Sk1mble** [comment]
The only way that can happen is if their map pack has actors in it which
aren't Fate Core Official actors.

**Comment by Sk1mble** [comment]
Here is the problem. This is an excerpt from the compendium containing
actors:
[image: image.png]
As you can see, it's actor type 'npc' to represent a church wall?

Furthermore, it looks like it's an actor in the D&D format. Technically
therefore I think this module requires you to be using the D&D module for
it to work. I think it will break for any system that doesn't have the
'npc' actor type and which has a different data schema.

I'm afraid this is a can't/won't fix for Fate Core Official.

Richard

**Comment by jasharen** [comment]
Ok thanks
