### ISSUE TITLE
won't update to 4.3.24

### ISSUE THREAD

**Issue by miromonti** [Sk1mble/fate-core-official#28]
I'm given this opportunity to update to 4.3.24...
![Screen Shot 2022-03-24 at 4 23 45 PM](https://user-images.githubusercontent.com/38819125/160026337-ca11c4a9-e8d3-48b7-a265-a99d68a5cfa2.png)

...Which I accept. But when the process is done, no update occurred:
![Screen Shot 2022-03-24 at 4 24 39 PM](https://user-images.githubusercontent.com/38819125/160026522-2cb848e6-20d1-4b52-8026-3f82636971d3.png)

Needs fixing.

FoundryVTT Version 9 - Build 255

**Comment by Sk1mble** [comment]
Hi, give it another try. It had the old version release in the manifest still.

**Comment by miromonti** [comment]
I tried the update cycle and there's a new alert:
![Screen Shot 2022-03-25 at 2 32 29 PM](https://user-images.githubusercontent.com/38819125/160204178-c8315bb5-0c2a-4e89-bc43-09a4517383ec.png)

Foundry 10 is barely into prototyping (as of two days ago). I'm not a developer and will continue with version 9 until v10's wide release later. In the meantime, can I get Fate Core Official 4.3.24 another way?

Or, is Fate Core Official 4.3.22 okay to use in the meantime? If the difference between it and x.24 is not literally game changing nor significant to game mechanics, then I'll wait.

**Comment by Sk1mble** [comment]
4.22 IS fine, there are just a couple of very small bug fixes between that
and 4.24, but I haven't released version 4.4.0 officially yet!

It must be detecting 4.4.0 from the manifest in my github, which is a bit
frustrating.

Anyway, you can explicitly install 4.2.4 by manually installing from:
https://raw.githubusercontent.com/Sk1mble/fate-core-official/v4.3.24/system.json
- paste that into the manual update field and you should be good to go.

Thanks,

Richard

**Comment by miromonti** [comment]
Believe it or not, the manual method installed version 4.3.22. I uninstalled and manually applied the .json. Twice. 

I think I'll stop here. 😄 

As you said, 4.3.22 is fine, so I won't sweat it. Thanks for your attention and patience.

Daniel.
