### ISSUE TITLE
Cards faces not working

### ISSUE THREAD

**Issue by Honmaru12** [Sk1mble/fate-core-official#29]
Hello Sk1mble,

first of all, thank your very much for your work and the constant updating of the system.

I´ve sadly found that, for any reason, looks like with Fate Core Official as game system the VTT Foundry Cards tool seems to break up.

As you try to create a card, you can add a "back" picture, but it just wont allow you to add any "face" picture:

![1](https://user-images.githubusercontent.com/101930694/160680072-c1c28e71-4bd1-45ef-ab32-97a89194c624.PNG)

You can try to load any image, but it will ignore it and load anything. I´ve tried uninstalling every module, testing with different picture´s formats....and it doesnt work either. 

However, the Foundry Card system works normally with every other game systems I tried:

![2](https://user-images.githubusercontent.com/101930694/160680792-ceb9f2f2-1994-468d-a2b4-24c57e7daf64.PNG)

I await for your answer, and thank you in advance.

**Comment by Sk1mble** [comment]
Hi,

I need more information, please.

Which version of Foundry are you running?
Which version of Fate Core Official?
Are there any errors in the system console (use F12 to pull this up on a
Windows PC; you'll need to look up the shortcut if you're on a different
type of device)

Thanks,

Richard

**Comment by Honmaru12** [comment]
These are my versions:

![3](https://user-images.githubusercontent.com/101930694/160693508-bf11de3f-16ce-4770-98b3-cf549c1737cf.PNG)

and about the system console error, it doesn´t show anything; as you click on the "load picture" button, it show "Rendering Filepicker", but doesn´t do anything when selecting any pic.

![4](https://user-images.githubusercontent.com/101930694/160694021-832f53c9-d27b-4fd7-a06c-ef615b6174cf.PNG)

Thank you.

**Comment by Sk1mble** [comment]
Okay, thanks. I have been able to replicate this. I'm investigating, but it
seems to be an issue with the text being saved to the text box rather than
anything more serious. As a workaround, after selecting the image you want
but before clicking 'select file' you can copy and paste the text box here
from the file picker directly into the face image box and it will work fine:

[image: image.png]

I'll see if I can figure out what's going on.

Thank you.

Richard

**Comment by Sk1mble** [comment]
After hours of bug hunting I found the issue and have fixed this. Version 4.3.25 will not have the same problem.
