### ISSUE TITLE
Question: German Fate World "Märchenkrieger LOS!"

### ISSUE THREAD

**Issue by Talaren** [Sk1mble/fate-core-official#3]
Hello,

I have a question how I could best implement this?
The rulebook is a mixture of FATE CORE and TURBO FATE.
Each player basically two character sheets.
The first one depicts the human, the second one depicts the fairy tale character.
The makers of the rulebook have illustrated this with 2 FATE sheets, one upside down, one right side up, so that you can only read one of them at a time.

With humans, everything is the same as in FATE CORE.
The problem is the second arc of the fairy tale character.
With them, it's not what they do that counts, but how they do it.
e.g. Sharp, Treacherous, Powerful

I can still map that with the skills, I add them to the skills from FATE CORE.

It gets more difficult with the superpowers of the character, because each character gets 4 points for superpowers.
A super power can cost between 1 and 4 points depending on how powerful it is.

Do you have an idea how I could map this best?
Thanks for any tips or hints.

Character sheet: https://faterpg.de/download/offiziellesmaterial/fate_core,_turbo-fate,_fate_accelerated/maerchenkrieger-los-Charakterbogen.pdf

**Comment by Sk1mble** [comment]
Hello! One way to do this would be to start with a blank character sheet as your template and build two Extras for each character. The first would reflect the skills, aspects, etc. of the human form. and the other their fairy tale character. You would then be able to flip between them by turning one extra off and other one on.

The super powers just sound like stunts?

**Comment by Talaren** [comment]
Thanks for the tip.
That could work.

Yes super power is a stunt. But limited by count, but with points, one powerful stunt cost more points, as a default stunt
e.g. fly (1) Breath of fire(2) the summary is (4) it is the same as the free stunts

**Comment by Sk1mble** [comment]
Right, and stunts can cost more than one refresh.
