### ISSUE TITLE
Exporting settings with the checkbox in module settings doesn't work

### ISSUE THREAD

**Issue by Blorgx3** [Sk1mble/fate-core-official#31]
The firefox developer console showed an error about something unspecified not being a "registered game setting" and the export popup didn't open.  I was able to solve this by editing fcoConstants.js and changing the variable name "fu_roll-formulae" to "fu-roll-formulae" on lines 306 and 307.

Aside from this relatively minor quibble I'm very pleased with and grateful for your work on this, thank you very much for doing it!

**Comment by Sk1mble** [comment]
Thank you, I have fixed this in v4.3.26.
