### ISSUE TITLE
Can't edit or delete skill with "~" character

### ISSUE THREAD

**Issue by gutzumerken** [Sk1mble/fate-core-official#33]
First: thank you for Fate core official and your hard work! :)

Bug: I set the name of a skill in the "Setup Skills" menu to "~  quick". Now I can't change the name of the skill anymore nor delete it...
Is there any way to "reset" the skill list or get rid of that skill?
![skillbug](https://user-images.githubusercontent.com/109515598/179483670-13305b5d-03ab-4a02-afe3-bdf9d4934a51.jpg)

Another request: Pls allow to manually sort the skill list so we don't have to put numbers oder special characters (like ~ ^^) in front of the names to sort them ;P

**Comment by Sk1mble** [comment]
Hi, I can help you to fix your broken skills, but ideally would do this by logging on to your server so I can manipulate the skill data.

I can't see myself adding the ability to sort skills manually at this time; this would require the addition of a secondary data item per skill which would track its sort order. This wouldn't be used by a majority of Fate implementations and would require a very significant rework of the way the skill data is stored. 

I'm unsure what has caused the skills to break here, but will know more when I can review your live data. Alternatively, you can export your skills by going to  the 'export all skills' option in the skill edit dialog:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/1439478/179617717-00dc66f3-a5af-4089-a445-8a16800afd8c.png">

**Comment by gutzumerken** [comment]
Hey,
we host the game on forge-vtt.com. So as far as I understand you can't log on into the server itself (?).
But I can give you my userdata/PW if that helps.
Here is the export of the skill data:
{
     "/Clever": {
          "name": "/Clever",
          "description": "",
          "overcome": "",
          "caa": "<p><br></p>",
          "attack": "<p><br></p>",
          "defend": "<p><br></p>",
          "pc": true
     },
     "*TECHnology": {
          "name": "*TECHnology",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "*ROGUISH": {
          "name": "*ROGUISH",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "*MARTIAL": {
          "name": "*MARTIAL",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "*PARAnormal": {
          "name": "*PARAnormal",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "/Flashy": {
          "name": "/Flashy",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "/Forceful": {
          "name": "/Forceful",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "+Careful": {
          "name": "+Careful",
          "description": "<p><br></p>",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "~  Quick": {
          "name": "Quick",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     },
     "~   Quick": {
          "name": "Quick",
          "description": "",
          "overcome": "",
          "caa": "",
          "attack": "",
          "defend": "",
          "pc": true
     }
}

To sort the skills by different amounts of * is a good idea. Way safer than strange characters ;)

**Comment by gutzumerken** [comment]
Can you replicate the problem when you name one of your skills "~ XYZ"?

**Comment by Sk1mble** [comment]
Example:

"Quick": {
"name": "Quick",
"description": "",
"overcome": "",
"caa": "",
"attack": "",
"defend": "",
"pc": true
}

I suspect the issue is that tilde is the bitwise not operator in JavaScript.

**Comment by gutzumerken** [comment]
Hm..
How do I clear all skills? I cant delete the ~ skills with the delete button..

I think I will export my data, crate a new game, import everything except the "~" skills and never ever use ~ again ^^

**Comment by Sk1mble** [comment]
If you select the option in the settings menu for "clear or override all
skills" that should do it, otherwise use
game.settings.set("fate-core-official", "skills", {})  in a code macro or
the console to clear them.

**Comment by gutzumerken** [comment]
Okay, thank you for your help! Much appreciated!
