### ISSUE TITLE
Unable update to 4.4.22

### ISSUE THREAD

**Issue by phantagor** [Sk1mble/fate-core-official#35]
I hope that just not me, but i seek to be stuck with version 4.4.08. i get thr message that an update is available (in the game session, telling me the newest uodate is 4.4.2), it seems to even update but stays at 4.4.08 ...

**Comment by Sk1mble** [comment]
That sounds like it is probably a Foundry bug. The best way forward is to
uninstall the system and then reinstall it fresh. This won't erase any of
your data.

**Comment by phantagor** [comment]
I tried that, twice without success... If you click on the manifest url (of version 4.4.22) it spews out the old version too

"minimumCoreVersion":"10.275",
  "version": "4.4.08",
  "scripts": ["

**Comment by phantagor** [comment]
![image](https://user-images.githubusercontent.com/7268421/191900756-933adcf0-89df-4cdb-a783-13b42d7472de.png)

![image](https://user-images.githubusercontent.com/7268421/191900788-60a7a372-c567-430b-8332-46e88f91ea6e.png)
![image](https://user-images.githubusercontent.com/7268421/191900963-fd894f4c-4e5b-4d50-849f-424ee5050b7a.png)

As you can see, Foundry seems to have the version 4.4.22 in its database, but upon installing the system, it shows as 4.4.08. When i then enter my game world, it still gives me the pop ip,. that a new version is available. And that is after having uninstalled and reinstalled it...

**Comment by Sk1mble** [comment]
Ok, I've identified the problem but have no idea how it occurred. The
version number in the manifest for that release has reverted for some
reason.

I need to ensure that the rest of the code on my repo is correct and then
fix the manifest. I'll let you know when it's done.

Sorry for the inconvenience.

**Comment by phantagor** [comment]
no worry mate, i am just happy that the issue is identified and can be fixed :D

**Comment by Sk1mble** [comment]
I've fixed it, might take a bit for the file to update in the Foundry
cache. It was a dumb error; I accidentally applied the tag to the wrong
release in GitHub desktop.

You can definitely install manually right now with the main manifest at
https://raw.githubusercontent.com/Sk1mble/fate-core-official/main/system.json

Sorry again and many thanks for the heads up!

Richard

**Comment by phantagor** [comment]
Thanks mate, it was already in the cache, good work!
