### ISSUE TITLE
Refresh Player Fate Points, Fate Utilities and Character Sheets

### ISSUE THREAD

**Issue by phantagor** [Sk1mble/fate-core-official#36]
Might just be an issue on my configuration, but it seems that while Fate Utilities keeps Track of Player Fatepoints, it does not update the character sheets individualy.
![image](https://user-images.githubusercontent.com/7268421/191915520-1f01e2ad-6bdf-4113-a777-61a7d4bf58b8.png)

I am not sure if this is on purpose or not, but it would make more sense, that Fatepoints spend should be updating on both the utilities and the character sheet?

Also, it seems that hitting "Refresh  Player Points" does not Refresh them, they just stay at Zero.

Same btw forStress: Fate Utilities clears fleeting stress tracks, but not on the character sheets:

![image](https://user-images.githubusercontent.com/7268421/191915860-1ead767c-909c-46f1-bc4c-c280f0a64dd2.png)

Sorry for causing more work ;)

**Comment by Sk1mble** [comment]
This is working as expected on my installation. Could I please have a GM
login on your world so I can investigate what's happening?

**Comment by phantagor** [comment]
Ah, sure yes...IP http://94.255.213.111:30000/ ,
use God Emperor of Mankind, PW is: interim

**Comment by Sk1mble** [comment]
Were you by any chance tabbing out of the fate points field after changing
it? That didn't work, only if you hit enter or clicked out. I'm pushing a
release shortly that disabled tabbing. Looking into this did help me fix a
bug that's been annoying me for literally months that I couldn't pin down
though, anyway!

**Comment by Sk1mble** [comment]
I've pushed 4.4.23 which improves the behaviour of FateUtilities in this respect. Let me know if you run into any more difficulties. I'm very active on the Foundry discord, so that's a great place to get rapid responses to any issues you may have or get bug support.

https://discord.gg/foundryvtt
