### ISSUE TITLE
Roll from Stunts doesn't interact with modified Roll Dialogue

### ISSUE THREAD

**Issue by BasiliskOnline** [Sk1mble/fate-core-official#37]
I have the modified roll Dialogue set up to always pop up, which works from the skills roll, but when you roll using the stunts, it bypasses it and doesn't pop up the Modified Roll Dialogue, which would be incredibly useful as i set up for #iHunt which occassionally uses a alternate die pool.
Thanks for the great work!

**Comment by Sk1mble** [comment]
That's as intended. The modified roll dialogue allows you to select
relevant stunts.
