### ISSUE TITLE
Variable Initiative

### ISSUE THREAD

**Issue by BasiliskOnline** [Sk1mble/fate-core-official#39]
In Settings there is a default for Initiative Skill, however you can only choose 1, despite in most Fate games what is used for initiative depends on the *type* of conflict (Notice for Physical and Empathy for Mental conflicts in Fate Core, for instance) 

Was wondering about QoL improvements allowing that to be set to multiple skills and then a pop up (or other way, initiative button next to the skill? or an initiative section on the sheet?) when rolling initiative to set that to the skill appropriate for the conflict?

Also maybe a character-specific option is better because Stunts could also lead to alternate initiatives?

**Comment by Sk1mble** [comment]
Hi,

The initiative skill automation is rather vestigial as I'm strongly of the
opinion that everyone should move to the initiative style used in
Condensed, which is often called Popcorn, Balsera, or Elective Order Action.

Having said that, to help you out if you want to keep using the old school
version of initiative, here is a simple macro that will alternate the
initiative skill between two values when flipped.

let skill = game.settings.get("fate-core-official","init_skill")
if (skill == "Notice") {
    game.settings.set("fate-core-official","init_skill","Empathy")
    ui.notifications.info("Initiative skill set to Empathy");
}
if (skill == "Empathy") {
    game.settings.set("fate-core-official","init_skill","Notice")
    ui.notifications.info("Initiative skill set to Notice");
}

In addition to this, it wouldn't be too hard to write a macro that also
looks at each combatant and checks for ties and then checks the
tie-breaking skill before setting initiative, but I will leave that as an
exercise for you. You would need to look at the game.combat.combatants list.

Hope that helps.

Richard

**Comment by BasiliskOnline** [comment]
Thanks for the help!
