### ISSUE TITLE
Extras and Items

### ISSUE THREAD

**Issue by ScottUlmer** [Sk1mble/fate-core-official#40]
Hello, Extras does not seem to be working as all you can do is add new and delete, you cannot edit or add descriptive text. I know Fate doesn't really have an inventory system, but currently Foundry Items is broken. I can create an item (name only). I cannot edit the image, descriptions, anything. After creating the item I cannot rename the item. When dragging an item to the character sheet it does get added to the Extras tab (good) but you can't edit, view, or anything else.

https://user-images.githubusercontent.com/29180106/203416264-f5719644-8a91-4c2c-a4ec-b9a1bc445b32.mp4

**Comment by Sk1mble** [comment]
I'm aware of this and will push a fix momentarily.
