### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jasharen** [Sk1mble/fate-core-official#42]
Hey Skimble,
Is it possible to offer a default a settings value for a default description? It would act as a template.

I have a formatted html that I drop into each new actor, that has a more traditional race, sex, height weight etc fields. It works well, but is a pain to add to each new actor.

Thanks!

**Comment by Sk1mble** [comment]
I'm definitely not going to add a setting for that, but you could do it very easily with a macro where you click on a token and then click on the macro and it sets the description for the  character. You could also do this in a world script that hooks into the character creation process. If you need help to do these things, ask on the Foundry Discord.

https://discord.gg/foundryvtt

**Comment by Sk1mble** [comment]
This macro will set the description of all selected tokens to the HTML between the backticks shown here:

let t = canvas.tokens.controlled;
for (let token of t){
    token.actor.update({
        "system.details.description.value":
        `<strong>Race: </strong>`
    })
}
