### ISSUE TITLE
Delete free invokes

### ISSUE THREAD

**Issue by Astamariymelrock** [Sk1mble/fate-core-official#43]
Hi, is it possible to somehow remove the inscription on the aspect (free invokes). I have not found anywhere how to do this. The inscription takes up a lot of space and is annoying.

**Comment by Sk1mble** [comment]
Are you asking how to remove the text 'free invokes' from aspect labels?

**Comment by Astamariymelrock** [comment]
да, текст просто занимает

**Comment by Astamariymelrock** [comment]
yes, the text just takes up a lot of space

**Comment by Sk1mble** [comment]
There is no straightforward and easy way to remove this as it's baked into
the aspect labels in the code. You could replace the
fate-core-official.freeinvokes and fate-core-official.freeinvoke entries in
the system's lang/en.json file with "" to make it an empty string, but this
will also cause the phrase to be empty elsewhere in the system as well, and
you'd have to re-edit the language file every time you updated the system.
