### ISSUE TITLE
Closing Character Sheet

### ISSUE THREAD

**Issue by NeuralDecker** [Sk1mble/fate-core-official#52]
Hi, 

we are having some trouble, two out of five characters can't close their character sheet again. I as Gamemaster, have the same problem. I have to reload the page again, but as soon as I reopen it again, same problem.

And we also noticed that I can't edit the Aspects, Tracks, and Stunts (so the gear symbol and so on don't do anything).

**Comment by Sk1mble** [comment]
This is usually caused by a corrupted data file for the character. Send me
an export of an affected character and I'll take a look.

**Comment by Sk1mble** [comment]
I've made some significant changes in the back end that should prevent this from happening once the character is migrated.
