### ISSUE TITLE
[Bug] Can't edit Linked Skills

### ISSUE THREAD

**Issue by mjanschek** [Sk1mble/fate-core-official#54]
I'm currently setting up a game world using this system (great work!) I've encountered a bug trying to set link skills for Tracks, As shown in the screenshot (version details also displayed there)

![grafik](https://github.com/Sk1mble/fate-core-official/assets/1671175/7dd8c809-91f8-4401-a983-02275cc4c63e)

**Comment by Sk1mble** [comment]
Hi, that's a missing s off of 'fcoConstants' in the relevant line. If you
have a local installation you can temporarily fix that, but l will release
an edited version in the next couple of hours.

Thanks for bringing this to my attention,

Richard

**Comment by Sk1mble** [comment]
Hi Michael,

This is fixed in v4.4.47 which should be available now.

Thanks,

Richard
