### ISSUE TITLE
Cannot add track to custom category

### ISSUE THREAD

**Issue by kondziu** [Sk1mble/fate-core-official#56]
**Problem**

I cannot add tracks to custom categories.

**Reproduction**

I create a new category of tracks:

![Screenshot from 2023-11-19 14-17-52](https://github.com/Sk1mble/fate-core-official/assets/50334/145337ff-8dbc-4828-bbd7-037ca66ee1cc)

I attempt to create a new track in the new category:

![Screenshot from 2023-11-19 14-18-06](https://github.com/Sk1mble/fate-core-official/assets/50334/7672d377-b55a-44d6-b429-1756aa5b502f)

![Screenshot from 2023-11-19 14-18-53](https://github.com/Sk1mble/fate-core-official/assets/50334/2cfb4405-89dc-4db7-81f4-50806b84e249)

The new track is not created:

![Screenshot from 2023-11-19 14-19-25](https://github.com/Sk1mble/fate-core-official/assets/50334/8dc96f33-0223-4251-bdc7-068a2a815d4e)

**Notes**

I *think* this worked before (same version), but I'm not 100% sure. If I broke something, I don't know how to check.

I can create tracks in Combat and Other just fine.

The error is not indicated in other ways than through the console.

**Version information**

Fate Core Official 4.5.0.6
Foundry Virtual tabletop 315Version 11 Stable

**Comment by Sk1mble** [comment]
I haven't been able to replicate this one, but my theory is that something
has gone wrong with your track category setting. Please could you show me
the contents of game.settings.get("fate-core-official", "track_categories")

Thanks,

Richard

**Comment by kondziu** [comment]
```js
>> game.settings.get("fate-core-official", "track_categories")
Object { Combat: "Combat", Other: "Other", Test: "Test" }
```

**Comment by Sk1mble** [comment]
Hmm, based on that it should be fine, as the track validation gets the list
of eligible categories from that list, by key. I'm out with my family at
the moment but I'll investigate more later.

**Comment by kondziu** [comment]
Thanks. And absolutely no hurry at all, as far as I'm concerned.

**Comment by Sk1mble** [comment]
Good news, I was able to replicate this, too. Was unable to save a track to a newly created cateogry because the list of valid categories was loaded on start-up rather than dynamically. You would have been able to add tracks to that category after a refresh. I've modified the functionality in 4,5.07 so that the list of categories is dynamically generated when the model is tested.
