### ISSUE TITLE
Wrong number of boxes displayed by track

### ISSUE THREAD

**Issue by kondziu** [Sk1mble/fate-core-official#58]
**Problem**

When editing the number of boxes displayed next to a track in the character sheet, the number of displayed boxes is sometimes different than the number in the settings.

**Reproduction**

I edit a track in a character sheet, I change the number in the field *Boxes* from `5` to `9` and save the settings.

![Screenshot from 2023-11-26 01-22-43](https://github.com/Sk1mble/fate-core-official/assets/50334/d9935b6d-ba38-4653-a96e-3d2ecac7750b)

![Screenshot from 2023-11-26 01-23-31](https://github.com/Sk1mble/fate-core-official/assets/50334/b7a9253f-f7d6-4afa-890b-7c0d19e47a78)

After editing, the track has 8 boxes in the character sheet:

![Screenshot from 2023-11-26 01-23-56](https://github.com/Sk1mble/fate-core-official/assets/50334/2195fe88-b5fc-4c10-a9d3-92b15943dac8)

**Notes**

I don't see any errors in the console.

I can get the sheet to display 9 boxes by changing the setting from 5 to 10, and then changing it again down to 9.

It seems that the difference between expected and actual number of boxes has something to do with the number of displayed rows.  Some examples:

| Previous value | Set value | Rendered boxes | Note |
| :--  | :-- | :--  | :-- |
| 5   |  9  | 7 + 1|  |
| 5  | 10 | 7 + 1 | |
| 10 | 20 |  7 + 7 + 1 | when previous value was rendered incorrectly as 7 + 1 |
| 10 | 20 | 7 + 7 + 2 | when previous value was rendered correctly as 7 + 3 |
| 20 | 30 | 7 + 7 + 7 + 2 |
| 3 | 5 | 5 | ok |
| 5 | 7 | 7 | ok |
| 7 | 8 | 7 + 1 | ok |
| 8 | 9 | 7 + 2 | ok |

**Version information**

Fate Core Official 4.5.0.8
Foundry Virtual tabletop 315Version 11 Stable

**Comment by Sk1mble** [comment]
This was an error in the logic that updated track box values when the number of them changed, the number of rows was a red herring. You should find this is fixed in v4.5.09.

**Comment by kondziu** [comment]
Sorry for spotlighting the red herring.

**Comment by Sk1mble** [comment]
It's fine, I knew that wasn't the issue so didn't waste any time on it, I
just thought you should know for future reference. The boxes are just
wrapping, there's no clever display logic.

**Comment by kondziu** [comment]
Looks fixed to me.
