### ISSUE TITLE
Update fails due to non-existent version 4.6 on fresh system installation 

### ISSUE THREAD

**Issue by r-valyar** [Sk1mble/fate-core-official#59]
During regular check for update the following message started to appear for the Fate system. It is looking for what appear is nonexistent version.

![image](https://github.com/Sk1mble/fate-core-official/assets/63558984/d369b662-4771-4820-b8e1-cf5d92de47b0)

**Comment by Sk1mble** [comment]
I hadn't released it and Foundry didn't know that. It has now been released (now 4.6.1)
