### ISSUE TITLE
Updtating in some foundry cause an Warning: SETUP.PackageUpdateCoreundefined f

### ISSUE THREAD

**Issue by gandb** [Sk1mble/fate-core-official#61]
And the version not update for the last release.
![2024-05-16 19_13_20-Foundry Virtual Tabletop](https://github.com/Sk1mble/fate-core-official/assets/8648403/d7549dd0-0d28-4c05-a748-86157f5fefe6)

![image](https://github.com/Sk1mble/fate-core-official/assets/8648403/effce58d-3b06-4982-8007-5de019ba5f07)

**Comment by Sk1mble** [comment]
This is a known bug in Foundry v11. It doesn't like being told the next
release only works in v12 when v12 is only available as a testing release.

You don't need the latest Fate Core Official unless you are running v12 of
Foundry.

Thanks,

Richard

**Comment by gandb** [comment]
Thanks
