### ISSUE TITLE
[Feature Request] Stunt Order Control in Item Interface

### ISSUE THREAD

**Issue by jdgcoop** [Sk1mble/fate-core-official#62]
In the item management interface, aspects have a re-order interface and stunts re-order on their own without user input or control.  

Is it possible to add a "move up" and "move down" button set to control the list order of stunts?  Or offer multiple sort options? It seems like the current sort is "last in, first out" without any user controls.  Thank you.

**Comment by Sk1mble** [comment]
This button switches between 'order added' and 'sort by name'.

[image: image.png]
[image: image.png]
