### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by XaverStiensmeier** [Sk1mble/fate-core-official#63]
my own imple**mne**tation -> my own **implementation**

**Comment by Sk1mble** [comment]
Where is this exactly? The text of journal article pages is not trivially
searchable.

**Comment by XaverStiensmeier** [comment]
My bad. I was referring to the readme https://github.com/Sk1mble/fate-core-official/blob/main/README.md#1-what-is-fate-core-official
